// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSrZPXvuOADcu8kSJAz9bXsNwCUDcRCsE',
    appId: '1:954499424860:web:d80db08ed8e874928abc99',
    messagingSenderId: '954499424860',
    projectId: 'chat-app-51d68',
    authDomain: 'chat-app-51d68.firebaseapp.com',
    storageBucket: 'chat-app-51d68.appspot.com',
    measurementId: 'G-5VQJTWZ7R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxTYwx0yAOZjsr1kxUebpZlOjuNvqfklA',
    appId: '1:954499424860:android:9613701658abf2a08abc99',
    messagingSenderId: '954499424860',
    projectId: 'chat-app-51d68',
    storageBucket: 'chat-app-51d68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-CYcPyxkO-FwLU-wtEH1NAntSa7kXLsA',
    appId: '1:954499424860:ios:379c75cb3042a7458abc99',
    messagingSenderId: '954499424860',
    projectId: 'chat-app-51d68',
    storageBucket: 'chat-app-51d68.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-CYcPyxkO-FwLU-wtEH1NAntSa7kXLsA',
    appId: '1:954499424860:ios:379c75cb3042a7458abc99',
    messagingSenderId: '954499424860',
    projectId: 'chat-app-51d68',
    storageBucket: 'chat-app-51d68.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSrZPXvuOADcu8kSJAz9bXsNwCUDcRCsE',
    appId: '1:954499424860:web:ec072774002148fa8abc99',
    messagingSenderId: '954499424860',
    projectId: 'chat-app-51d68',
    authDomain: 'chat-app-51d68.firebaseapp.com',
    storageBucket: 'chat-app-51d68.appspot.com',
    measurementId: 'G-K6N0ZR3GHC',
  );
}
